language: android
jdk: oraclejdk8

addons:
  apt:
    packages:
      - lynx

env:
 global:
    - ANDROID_API=25

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-$ANDROID_API
    - extra-android-support
    - extra-android-m2repository


script:
  - ./gradlew build
  - if [ -f /home/travis/build/richardszabo/Ponthatar/app/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/richardszabo/Ponthatar/app/build/outputs/lint-results-debug.html; fi
  - ./gradlew test
  - if [ -f /home/travis/build/richardszabo/Ponthatar/app/build/reports/tests/testDebugUnitTest/index.html ]; then lynx -dump /home/travis/build/richardszabo/Ponthatar/app/build/reports/tests/testDebugUnitTest/index.html; fi

